# Generated by Django 3.0.8 on 2020-09-02 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip_places', '0008_auto_20200901_1651'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_from', models.CharField(blank=True, max_length=35, verbose_name='The point where the journey was started')),
                ('journey_to', models.CharField(blank=True, max_length=35, verbose_name='The point where the journey was finished')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Describe your journey')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('particapants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Particapants of the journey')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_places.Place', verbose_name='Place that is connected with the journey')),
            ],
            options={
                'verbose_name': 'Journey',
                'verbose_name_plural': 'Journeys',
                'ordering': ('-timestamp',),
            },
        ),
    ]
