# Generated by Django 3.0.8 on 2020-09-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0008_auto_20200901_1651'),
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='who_added_the_journey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='who_added', to='trip_places.Place', verbose_name="The person who has created the journey's page"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
