# Generated by Django 3.0.8 on 2020-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0003_auto_20200902_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='data_of_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='date_of_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Describe your journey'),
        ),
    ]
