# Generated by Django 3.0.8 on 2020-09-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0005_auto_20200903_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journeys.Journey')),
                ('particapant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='journey',
            name='particapants',
        ),
        migrations.AddField(
            model_name='journey',
            name='particapants',
            field=models.ManyToManyField(blank=True, through='journeys.Participant', to=settings.AUTH_USER_MODEL, verbose_name='Particapants of the journey'),
        ),
    ]
