# Generated by Django 3.0.8 on 2020-09-07 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0009_place_timestamp'),
        ('journeys', '0005_auto_20200903_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='place',
        ),
        migrations.AddField(
            model_name='journey',
            name='place_from',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='start_places', to='trip_places.Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journey',
            name='place_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='end_places', to='trip_places.Place'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_of_activity', models.CharField(blank=True, max_length=35, verbose_name='Description of activity')),
                ('date_of_start', models.DateField(null=True)),
                ('date_of_end', models.DateField(null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities', to='journeys.Journey')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip_places.Place')),
            ],
        ),
    ]
