# Generated by Django 3.0.8 on 2020-09-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_auto_20200907_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='description_of_activity',
            new_name='description',
        ),
    ]
