# Generated by Django 3.0.8 on 2020-09-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0006_auto_20200907_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='particapants',
            new_name='participants',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='particapant',
            new_name='participant',
        ),
    ]
