# Generated by Django 3.0.8 on 2020-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0007_auto_20200907_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
