# Generated by Django 3.0.8 on 2020-09-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0008_auto_20200907_1653'),
        ('journeys', '0007_auto_20200907_1721'),
    ]

    operations = [
    ]
