# Generated by Django 3.0.8 on 2020-09-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0009_merge_20200909_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
