# Generated by Django 3.0.8 on 2020-09-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0010_auto_20200909_1809'),
        ('journeys', '0008_auto_20200909_1740'),
    ]

    operations = [
    ]
