# Generated by Django 3.0.8 on 2020-09-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0009_place_timestamp'),
        ('journeys', '0011_merge_20200910_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='journey_to',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='The point where the journey was finished'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='place_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_places', to='trip_places.Place'),
        ),
    ]
