# Generated by Django 3.0.8 on 2020-09-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0009_place_timestamp'),
        ('journeys', '0014_auto_20200910_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='journey_from',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='The point where the journey was started'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='place_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_places', to='trip_places.Place'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='place_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_places', to='trip_places.Place'),
        ),
    ]
