# Generated by Django 3.0.8 on 2020-09-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0009_place_timestamp'),
        ('journeys', '0016_auto_20200910_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_of_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date_of_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Activities', to='journeys.Journey'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip_places.Place'),
        ),
    ]
