# Generated by Django 3.0.8 on 2020-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0018_auto_20200911_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Describe your journey'),
        ),
    ]
