# Generated by Django 3.0.8 on 2020-09-16 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeys', '0019_auto_20200911_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, through='journeys.Participant', to=settings.AUTH_USER_MODEL, verbose_name='Particapants of the journey'),
        ),
    ]
