# Generated by Django 3.0.8 on 2020-09-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0010_auto_20200916_1620'),
        ('journeys', '0019_auto_20200911_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='journeys.Journey'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trip_places.Place'),
        ),
    ]
