# Generated by Django 3.0.8 on 2020-09-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0020_auto_20200916_1810'),
        ('journeys', '0020_auto_20200916_1651'),
    ]

    operations = [
    ]
