language: python

dist: bionic

python:
  - "3.8"
  
install:
  - pip install poetry
  - poetry install

before_script: cd triplinker

env:
  - DEBUG=on
  - SECRET_KEY="dev"
  - DATABASE_URL=psql://test:test@127.0.0.1:5432/test
  - STATIC_URL=/static/

script:
  - pytest
