language: python

dist: bionic

python:
  - "3.8"
  
install:
  - pip install poetry
  - poetry install

services:
  - postgresql

before_script:
  - cd triplinker
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER test with encrypted password 'test';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres
  - psql -c "ALTER USER test createdb;" -U postgres
  - python manage.py migrate --noinput
  - bash celery.sh

env:
  global:
    - DEBUG=on
    - SECRET_KEY="dev"
    - DATABASE_URL=psql://test:test@127.0.0.1:5432/test
    - STATIC_URL=/static/

script:
  - pytest tests
  - python manage.py test
  - flake8
