# Generated by Django 3.0.8 on 2020-07-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlaccount',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='country',
            field=models.CharField(blank=True, choices=[('BY', 'Belarus')], max_length=25, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='hobbies',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Place of work'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='second_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='short_description',
            field=models.CharField(blank=True, default=0, max_length=500, verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='vkontakte',
            field=models.URLField(blank=True, null=True, verbose_name='VKontakte'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
