# Generated by Django 3.0.8 on 2020-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlaccount',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/user_main_photo', verbose_name='Profile image'),
        ),
    ]
