# Generated by Django 3.0.8 on 2020-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='hobbies',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Place of work'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='vkontakte',
            field=models.URLField(blank=True, null=True, verbose_name='VKontakte'),
        ),
    ]
