# Generated by Django 3.0.8 on 2020-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200716_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='country',
            field=models.CharField(blank=True, choices=[('BY', 'Belarus')], max_length=25, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='facebook',
            field=models.URLField(blank=True, default='', verbose_name='Facebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Hobbies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='place_of_work',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Place of work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='second_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Short description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='twitter',
            field=models.URLField(blank=True, default='', verbose_name='Twitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tlaccount',
            name='vkontakte',
            field=models.URLField(blank=True, default='', verbose_name='VKontakte'),
            preserve_default=False,
        ),
    ]
