# Generated by Django 3.0.8 on 2020-07-27 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200724_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
