# Generated by Django 3.0.8 on 2020-10-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tlaccount_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlaccount',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='AvatarTLAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='accounts/user_main_photo', verbose_name='Profile image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_avatar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AvatarTLAccount',
                'verbose_name_plural': 'AvatarsTLAccounts',
            },
        ),
    ]
