# Generated by Django 3.0.8 on 2020-07-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200728_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='place_of_work',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Place of work'),
            preserve_default=False,
        ),
    ]
