# Generated by Django 3.0.8 on 2020-10-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201005_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatartlaccount',
            name='profile_image',
            field=models.ImageField(default=None, upload_to='accounts/user_main_photo', verbose_name='Profile image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatartlaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_avatar', to=settings.AUTH_USER_MODEL),
        ),
    ]
