# Generated by Django 3.0.8 on 2020-07-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_friendrequest_friendssystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tlaccount',
            name='friends',
        ),
    ]
