# Generated by Django 3.0.8 on 2020-07-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200729_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Hobbies'),
            preserve_default=False,
        ),
    ]
