# Generated by Django 3.0.8 on 2020-07-23 17:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_tlaccount_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendssystem',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
