# Generated by Django 3.0.8 on 2020-10-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201005_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlaccount',
            name='motto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motto'),
        ),
    ]
