# Generated by Django 3.0.8 on 2020-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tlaccount_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='motto',
            field=models.CharField(blank=True, max_length=62, null=True, verbose_name='Motto'),
        ),
    ]
