# Generated by Django 3.0.8 on 2020-07-30 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200729_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlaccount',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_of_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tlaccount',
            name='people_which_follow',
            field=models.ManyToManyField(blank=True, related_name='people_whick_follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
