# Generated by Django 3.0.8 on 2020-07-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200729_1509'),
        ('accounts', '0008_auto_20200730_1447'),
    ]

    operations = [
    ]
