# Generated by Django 3.0.8 on 2020-10-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201009_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='accounts/user_gallery', verbose_name='Photos of place')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_of_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserPhoto (Gallery)',
                'verbose_name_plural': 'UserPhotos (Gallery)',
                'ordering': ('-timestamp',),
            },
        ),
    ]
