# Generated by Django 3.0.8 on 2020-08-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200802_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
