# Generated by Django 3.0.8 on 2020-10-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201009_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalqualities',
            old_name='qualities',
            new_name='quality',
        ),
    ]
