# Generated by Django 3.0.8 on 2020-08-07 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='people_which_follow',
            field=models.ManyToManyField(blank=True, related_name='people_which_follow_cur_usr', to=settings.AUTH_USER_MODEL),
        ),
    ]
