# Generated by Django 3.0.8 on 2020-08-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200807_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlaccount',
            name='can_get_message_from',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='User can get messages from:'),
        ),
    ]
