# Generated by Django 3.0.8 on 2020-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tlaccount_can_get_message_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tlaccount',
            name='can_get_message_from',
            field=models.CharField(blank=True, choices=[('Friends', 'Friends only'), ('All', 'All users')], max_length=12, verbose_name='You can get messages from:'),
        ),
    ]
