# Generated by Django 3.0.8 on 2020-08-24 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200823_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlaccount',
            name='strangers',
            field=models.ManyToManyField(blank=True, related_name='messages_strangers', to=settings.AUTH_USER_MODEL),
        ),
    ]
