# Generated by Django 3.0.8 on 2020-07-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
