# Generated by Django 3.0.8 on 2020-09-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to_user', to=settings.AUTH_USER_MODEL)),
                ('users_who_read_message', models.ManyToManyField(blank=True, related_name='readersOfMsg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(max_length=25, verbose_name='The name of group chat')),
                ('chat_image', models.ImageField(blank=True, null=True, upload_to='chat/main_chat_image', verbose_name='Main photo of chat')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('creator', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, default=None, related_name='get_chat_partns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GroupChat',
                'verbose_name_plural': 'GroupChats',
            },
        ),
    ]
