# Generated by Django 3.0.8 on 2020-08-19 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200815_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='message',
            name='users_who_read_messages',
            field=models.ManyToManyField(blank=True, related_name='readers_of_the_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
