# Generated by Django 3.0.8 on 2020-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200921_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='slug',
            field=models.SlugField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
