# Generated by Django 3.0.8 on 2020-08-19 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20200819_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='users_who_read_message',
            field=models.ManyToManyField(blank=True, related_name='readersOfMsg', to=settings.AUTH_USER_MODEL),
        ),
    ]
