# Generated by Django 3.0.8 on 2020-09-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupchat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
    ]
