# Generated by Django 3.0.8 on 2020-08-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200819_1714'),
        ('chat', '0005_auto_20200819_1841'),
    ]

    operations = [
    ]
