# Generated by Django 3.0.8 on 2020-09-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20200921_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_msges_from_user', to=settings.AUTH_USER_MODEL)),
                ('group_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.GroupChat')),
                ('to_users', models.ManyToManyField(related_name='group_chat_msges_to_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GroupChatMessage',
                'verbose_name_plural': 'GroupChatMessages',
            },
        ),
    ]
