# Generated by Django 3.0.8 on 2020-09-22 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_groupchatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='to_users',
        ),
        migrations.AddField(
            model_name='groupchatmessage',
            name='to_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_msges_to_users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
