# Generated by Django 3.0.8 on 2020-09-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_groupchatmessage_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatmessage',
            old_name='to_users',
            new_name='to_user',
        ),
    ]
