# Generated by Django 3.0.8 on 2020-09-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200922_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchatmessage',
            old_name='from_user',
            new_name='msg_from_user',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='to_user',
        ),
    ]
