# Generated by Django 3.0.8 on 2020-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200922_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='message',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
