# Generated by Django 3.0.8 on 2020-09-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_groupchatmessage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='images',
        ),
    ]
