# Generated by Django 3.0.8 on 2020-09-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_groupchatmessage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/pictures_of_messages', verbose_name='Picture of message')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.GroupChatMessage')),
            ],
            options={
                'verbose_name': 'MessagePhoto',
                'verbose_name_plural': 'MessagePhotos',
            },
        ),
    ]
