# Generated by Django 3.0.8 on 2020-09-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_messagephoto_name_of_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_message',
            field=models.ImageField(blank=True, null=True, upload_to='chat/pictures_of_messages', verbose_name='Picture of message'),
        ),
    ]
