# Generated by Django 3.0.8 on 2020-09-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_message_image_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image_message',
        ),
    ]
