# Generated by Django 3.0.8 on 2020-09-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_message_image_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/pictures_of_messages', verbose_name='Picture of message')),
                ('name_of_file', models.TextField(blank=True, null=True, verbose_name='The name image')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Message')),
            ],
            options={
                'verbose_name': 'DialogPhoto',
                'verbose_name_plural': 'DialogPhotos',
            },
        ),
    ]
