# Generated by Django 3.0.8 on 2020-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20201003_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmainphoto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
