# Generated by Django 3.0.8 on 2020-10-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_groupchatmainphoto_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchatmainphoto',
            options={'verbose_name': 'GroupChatMainPhoto', 'verbose_name_plural': 'GroupChatMainPhotos'},
        ),
        migrations.AlterField(
            model_name='groupchatmainphoto',
            name='group_chat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_main_photo_of_chat', to='chat.GroupChat'),
        ),
    ]
