# Generated by Django 3.0.8 on 2020-10-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20201003_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagePhoto',
            new_name='GroupChatMessagePhoto',
        ),
        migrations.AlterModelOptions(
            name='groupchatmessagephoto',
            options={'verbose_name': 'GroupChatMessagePhoto', 'verbose_name_plural': 'GroupChatMessagePhoto'},
        ),
    ]
