# Generated by Django 3.0.8 on 2020-10-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20201004_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchatmessagephoto',
            options={'verbose_name': 'GroupChatMessagePhoto', 'verbose_name_plural': 'GroupChatMessagePhotos'},
        ),
    ]
