# Generated by Django 3.0.8 on 2020-07-15 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripLinkerAccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=15, verbose_name='First name')),
                ('second_name', models.CharField(max_length=15, verbose_name='Second name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, verbose_name='Sex')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('country', models.CharField(choices=[('BY', 'Belarus')], max_length=25, verbose_name='Country')),
                ('place_of_work', models.DateField(null=True, verbose_name='Place of work')),
                ('short_description', models.CharField(max_length=500, null=True, verbose_name='Short description')),
                ('hobbies', models.CharField(max_length=250, null=True, verbose_name='Hobbies')),
                ('vkontakte', models.URLField(verbose_name='VKontakte')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
