# Generated by Django 3.0.8 on 2020-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notification_post',
            field=models.BooleanField(default=False),
        ),
    ]
