# Generated by Django 3.0.8 on 2020-09-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0024_auto_20200918_1540'),
        ('feed', '0003_post_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_journey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_of_journey', to='journeys.Journey'),
        ),
    ]
