# Generated by Django 3.0.8 on 2020-08-27 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
