# Generated by Django 3.0.8 on 2020-08-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0002_place_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_pic',
            field=models.ImageField(blank=True, null=True, upload_to='places/main_pic', verbose_name='Main picture of the place'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_pic', models.ImageField(blank=True, null=True, upload_to='places/photos_of_place', verbose_name='Photos of place')),
                ('place', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_of_place', to='trip_places.Place')),
            ],
        ),
    ]
