# Generated by Django 3.0.8 on 2020-09-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0009_place_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(choices=[('BY', 'Belarus'), ('US', 'United States of America'), ('CH', 'China')], max_length=25, verbose_name='The location of place'),
        ),
    ]
