# Generated by Django 3.0.8 on 2020-09-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_places', '0010_auto_20200916_1810'),
        ('trip_places', '0010_auto_20200916_1620'),
    ]

    operations = [
    ]
